services:
  db:
    image: mysql:8.0.31
    volumes:
      - /opt/test:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: banco1234
      MYSQL_DATABASE: banco
      MYSQL_USER: banco
      MYSQL_PASSWORD: banco
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: banco1234
  api:
    depends_on:
      db:
        condition: service_healthy
    image: tomcat:9.0.69
    volumes:
      - ./despliegue/api-banco.war:/usr/local/tomcat/webapps/api-banco.war
      - ./tomcat-logs:/usr/local/tomcat/logs
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: banco1234
      MYSQL_DATABASE: banco
      MYSQL_USER: banco
      MYSQL_PASSWORD: banco
  front:
    image: httpd:2.4-alpine
    ports:
      - '80:80'
    volumes:
      - ./www:/usr/local/apache2/htdocs
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
